tls:
  certificates:
    - certFile: "/etc/traefik/certs/_wildcard.dev.geekfactorio.com.pem"
      keyFile: "/etc/traefik/certs/_wildcard.dev.geekfactorio.com-key.pem"
    - certFile: "/etc/traefik/certs/_wildcard.dev.geekfactorio.ru.pem"
      keyFile: "/etc/traefik/certs/_wildcard.dev.geekfactorio.ru-key.pem"
    - certFile: "/etc/traefik/certs/dev.geekfactorio.com.pem"
      keyFile: "/etc/traefik/certs/dev.geekfactorio.com-key.pem"
    - certFile: "/etc/traefik/certs/dev.geekfactorio.ru.pem"
      keyFile: "/etc/traefik/certs/dev.geekfactorio.ru-key.pem"
