defaultEntryPoints = ["http", "https"]
[entryPoints.web] 
  address = ":80" 
  [entryPoints.web.http]
    [entryPoints.web.http.redirections]
      [entryPoints.web.http.redirections.entryPoint]
        to = "websecure"
        scheme = "https"

[entryPoints.websecure]
  address = ":443"

[[tls.certificates]]
  certFile = "/etc/traefik/ssl/_wildcard.geekfactorio.com.pem"
  keyFile = "/etc/traefik/ssl/_wildcard.geekfactorio.com-key.pem"
[[tls.certificates]]
  certFile = "/etc/traefik/ssl/_wildcard.geekfactorio.ru.pem"
  keyFile = "/etc/traefik/ssl/_wildcard.geekfactorio.ru-key.pem"

[api]
  insecure = true
  dashboard = true
