entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "websecure"
          scheme: "https"
  websecure:
    address: ":443"

api:
  insecure: true
  dashboard: true

providers:
  file:
    directory: "/etc/traefik/rules"
  docker:
    exposedByDefault: false
